export const SOCKET_GAME = {
  RECEIVE_ORIENTATION: 'RECEIVE_ORIENTATION',
  SEND_ORIENTATION: 'SEND_ORIENTATION',
};

export const SOCKET_MANAGE = {
  REGISTER_PLAYER_ID: 'REGISTER_PLAYER_ID',
  REGISTER_CLIENT: 'REGISTER_CLIENT',
  REGISTER_PLAYER: 'REGISTER_PLAYER',
  RESULT_REGISTER_PLAYER: 'RESULT_REGISTER_PLAYER',
};

// Socket built-in events are all lowercase
export const SOCKET_GENERAL = {
  CONNECT: 'connect',
  CONNECTION: 'connection',
  DISCONNECT: 'disconnect',
};
